/*
 * JSP generated by Resin-4.0.35 (built Tue, 12 Feb 2013 10:05:50 PST)
 */

package _jsp._bdp._pages;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _welcome__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
  String contextPath = (String) request.getContextPath();
			request.setAttribute("isMenu", "true");

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((contextPath ));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((contextPath));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((contextPath));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((contextPath));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((contextPath));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((contextPath));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((contextPath));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((contextPath));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((contextPath));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((contextPath));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((contextPath));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((contextPath));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((contextPath));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((contextPath));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((contextPath));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((contextPath));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((contextPath));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((contextPath));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((contextPath));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    out.print((contextPath));
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((contextPath));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((contextPath));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    out.print((contextPath));
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((contextPath));
    out.write(_jsp_string25, 0, _jsp_string25.length);
    out.print((contextPath));
    out.write(_jsp_string26, 0, _jsp_string26.length);
    out.print((contextPath));
    out.write(_jsp_string27, 0, _jsp_string27.length);
    out.print((contextPath));
    out.write(_jsp_string28, 0, _jsp_string28.length);
    out.print((contextPath));
    out.write(_jsp_string29, 0, _jsp_string29.length);
    out.print((contextPath));
    out.write(_jsp_string30, 0, _jsp_string30.length);
    out.print((contextPath));
    out.write(_jsp_string31, 0, _jsp_string31.length);
    out.print((contextPath));
    out.write(_jsp_string32, 0, _jsp_string32.length);
    out.print((contextPath));
    out.write(_jsp_string33, 0, _jsp_string33.length);
    out.print((contextPath));
    out.write(_jsp_string34, 0, _jsp_string34.length);
    out.print((contextPath));
    out.write(_jsp_string35, 0, _jsp_string35.length);
    out.print((contextPath));
    out.write(_jsp_string36, 0, _jsp_string36.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8128084403448394333L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bdp/pages/welcome.jsp"), -2029719145190235559L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("bdp/commons/statics.jsp"), -3934675670371445898L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string18;
  private final static char []_jsp_string32;
  private final static char []_jsp_string7;
  private final static char []_jsp_string26;
  private final static char []_jsp_string13;
  private final static char []_jsp_string19;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string30;
  private final static char []_jsp_string36;
  private final static char []_jsp_string21;
  private final static char []_jsp_string4;
  private final static char []_jsp_string28;
  private final static char []_jsp_string15;
  private final static char []_jsp_string27;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string29;
  private final static char []_jsp_string24;
  private final static char []_jsp_string11;
  private final static char []_jsp_string23;
  private final static char []_jsp_string17;
  private final static char []_jsp_string2;
  private final static char []_jsp_string9;
  private final static char []_jsp_string33;
  private final static char []_jsp_string20;
  private final static char []_jsp_string34;
  private final static char []_jsp_string35;
  private final static char []_jsp_string3;
  private final static char []_jsp_string22;
  private final static char []_jsp_string12;
  private final static char []_jsp_string25;
  private final static char []_jsp_string1;
  private final static char []_jsp_string10;
  private final static char []_jsp_string16;
  private final static char []_jsp_string31;
  private final static char []_jsp_string8;
  static {
    _jsp_string18 = "/resources/bdp/js/jquery/jquery-validate/jquery.validate.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string32 = "/resources/bdp/js/bdp/xmlTohtml.js\"></script>\r\n<!-- bootstrapvalidator \u8868\u5355\u9a8c\u8bc1 -->\r\n<link href=\"".toCharArray();
    _jsp_string7 = "/resources/bdp/bootstrap/datetimepicker/css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n<!--  \u5f15\u5165bootstrap-3.0.3.min.css,\u89e3\u51b3\u4e86\u4e0b\u62c9\u9009\u62e9\u6837\u5f0f\u95ee\u9898\u3001\u8868\u683c\u5b57\u4f53\u5168\u90e8\u52a0\u7c97\u95ee\u9898-->\r\n<link href=\"".toCharArray();
    _jsp_string26 = "/resources/bdp/bootstrap/js/summernote.js\"></script>\r\n\r\n<script src=\"".toCharArray();
    _jsp_string13 = "/resources/bdp/highchart/exporting.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string19 = "/resources/bdp/js/jquery/jquery-validate/messages_zh.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string6 = "/resources/bdp/bootstrap/css/bootstrap-multiselect.css\" rel=\"stylesheet\">\r\n<link href=\"".toCharArray();
    _jsp_string5 = "/resources/bdp/bootstrap/css/metisMenu.min.css\" rel=\"stylesheet\">\r\n<link href=\"".toCharArray();
    _jsp_string30 = "/resources/bdp/bootstrap/export/FileSaver.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string36 = "/resources/bdp/images/user.png\">\u7528\u6237\u7ba1\u7406\r\n			</a>\r\n		</li>\r\n		<li>\r\n			<a href=\"#\" onclick=\"openLink('\u89d2\u8272\u7ba1\u7406','Role/main.do')\">\r\n				<img src=\"../../resources/bdp/images/roles.png\">\u89d2\u8272\u7ba1\u7406\r\n			</a>\r\n		</li>\r\n    <li>\r\n      <a href=\"#\" onclick=\"openLink('\u5e7f\u544a\u4f4d\u7ba1\u7406','AdPlace/main.do')\">\r\n        <img src=\"../../resources/bdp/images/roles.png\">\u5e7f\u544a\u4f4d\u7ba1\u7406\r\n      </a>\r\n    </li>\r\n    <li>\r\n      <a href=\"#\" onclick=\"openLink('\u520a\u4f8b\u4ef7','AdPlacePrice/main.do')\">\r\n        <img src=\"../../resources/bdp/images/roles.png\">\u520a\u4f8b\u4ef7\r\n      </a>\r\n    </li>\r\n    <li>\r\n      <a href=\"#\" onclick=\"openLink('\u8282\u5047\u65e5\u6298\u6263','HolidayDiscount/main.do')\">\r\n        <img src=\"../../resources/bdp/images/roles.png\">\u8282\u5047\u65e5\u6298\u6263\r\n      </a>\r\n    </li>\r\n	</ul>\r\n</div>\r\n<script type=\"text/javascript\">\r\n	//\u6253\u5f00\u94fe\u63a5\r\n	function openLink(title,url) {\r\n		window.parent.window.addTab(title,url);\r\n	}\r\n</script>\r\n</body>\r\n</html>\r\n\r\n".toCharArray();
    _jsp_string21 = "/resources/bdp/js/jquery/jquery.ztree.excheck-3.5.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string4 = "/resources/bdp/css/orgStructTree/bootstrap/bootstrap-table.min.css\" rel=\"stylesheet\"  />\r\n<link href=\"".toCharArray();
    _jsp_string28 = "/resources/bdp/js/bdp/commons-operate.js\"></script>\r\n\r\n\r\n<!-- \u5f15\u5165\u5bfc\u51fa\u8868\u683c\u5230\u6587\u4ef6\u7684\u63d2\u4ef6 -->\r\n<script src=\"".toCharArray();
    _jsp_string15 = "/resources/bdp/js/bdp/orgStructTree/bootstrap/bootstrap-table-all.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string27 = "/resources/bdp/js/bdp/util.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string14 = "/resources/bdp/bootstrap/js/bootstrap.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string29 = "/resources/bdp/bootstrap/export/tableExport.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string24 = "/resources/bdp/bootstrap/datetimepicker/js/bootstrap-datetimepicker.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string11 = "/resources/bdp/js/jquery/jquery.min.js\"></script>\r\n<!--highChart  -->\r\n<script src=\"".toCharArray();
    _jsp_string23 = "/resources/bdp/bootstrap/js/bootstrap-multiselect.js\"></script>\r\n<!--\u65f6\u95f4\u63a7\u4ef6  -->\r\n<script src=\"".toCharArray();
    _jsp_string17 = "/resources/bdp/js/bootstrap-table/bootstrap-table-zh-CN.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string2 = "\";\r\n</script>\r\n\r\n<link href=\"".toCharArray();
    _jsp_string9 = "/resources/bdp/bootstrap/css/summernote.css\" rel=\"stylesheet\">\r\n<!--  bootstrap \u56fe\u6807-->\r\n<link href=\"".toCharArray();
    _jsp_string33 = "/resources/bdp/bootstrap/bootstrapvalidator/src/css/bootstrapValidator.css\" rel=\"stylesheet\" media=\"screen\">\r\n<script src=\"".toCharArray();
    _jsp_string20 = "/resources/bdp/js/jquery/jquery.ztree.core-3.5.min.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string34 = "/resources/bdp/bootstrap/bootstrapvalidator/src/js/bootstrapValidator.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string35 = "/resources/bdp/bootstrap/bootstrapvalidator/src/js/language/zh_CN.js\"></script>\r\n<style type=\"text/css\">\r\nul,li {\r\n		list-style: none;\r\n		margin: 0;\r\n		padding: 0;\r\n}\r\n\r\n.box {\r\n		width: 800px;\r\n		margin: auto;\r\n}\r\n\r\n.nav_link {\r\n        margin-top: 15px;\r\n		margin-left: 20px;\r\n		overflow: hidden;\r\n}\r\n\r\n.nav_link span {\r\n		float: left;\r\n		line-height: 30px;\r\n		font-size: 20px;\r\n		font-weight: bold;\r\n}\r\n\r\n.nav_link li {\r\n		float: left;\r\n		margin-right: 25px;\r\n		margin-left: 15px;\r\n		border-radius: 15px;\r\n		width: 130px;\r\n		height: 30px;\r\n		/* background-color: #555; */\r\n		line-height: 30px;\r\n		text-align: center;\r\n}\r\n\r\n.nav_link li a {\r\n		color: #333;\r\n		text-decoration: none;\r\n		font-size: 15px;\r\n}\r\n\r\n.nav_link li a:hover {\r\n		color: #2a6496;\r\n}\r\n\r\n.nav_link li a img{\r\n		height: 26px;\r\n		margin-right: 2px;\r\n}\r\n.main_ten {\r\n		overflow: hidden;\r\n		zoom: 1;\r\n		margin-top: 30px;\r\n}\r\n\r\n.title {\r\n	margin-left: 20px;\r\n	font-size: 20px;\r\n	font-weight: bold;\r\n	margin-bottom: 20px;\r\n}\r\n\r\n.caption {\r\n	text-align: center;\r\n}\r\n\r\n.thumbnail > img {\r\n   height: 100px;\r\n}\r\n\r\nhtml {\r\n  position: relative;\r\n  min-height: 100%;\r\n}\r\n#footer {\r\n  /* position: absolute; */\r\n  bottom: 0;\r\n  width: 100%;\r\n  height: 10px;\r\n  margin-top: 50px;\r\n}\r\n</style>\r\n</head>\r\n<body>\r\n<div class=\"nav_link\">\r\n	<ul>\r\n		<span>\u5feb\u901f\u5bfc\u822a\uff1a</span>\r\n		<li>\r\n			<a href=\"#\" onclick=\"openLink('\u7528\u6237\u7ba1\u7406','UserInit/main.do')\">\r\n				<img src=\"".toCharArray();
    _jsp_string3 = "/resources/bdp/css/zTreeStyle/zTreeStyle.css\" rel=\"stylesheet\">\r\n<link href=\"".toCharArray();
    _jsp_string22 = "/resources/bdp/js/jquery/jquery.ztree.exedit-3.5.min.js\"></script>\r\n<!--\u4e0b\u62c9\u9009\u62e9\u6846JS  -->\r\n<script src=\"".toCharArray();
    _jsp_string12 = "/resources/bdp/highchart/highcharts.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string25 = "/resources/bdp/bootstrap/datetimepicker/js/bootstrap-datetimepicker.fr.js\"></script>\r\n<!--\u5728\u7ebf\u7f16\u8f91\u5668  -->\r\n<script src=\"".toCharArray();
    _jsp_string1 = "\r\n<script type=\"text/javascript\">\r\n	var contextPath=\"".toCharArray();
    _jsp_string10 = "/resources/bdp/bootstrap/bower_components/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n\r\n<script src=\"".toCharArray();
    _jsp_string16 = "/resources/bdp/js/bootstrap-table/bootstrap-table-resize.js\"></script>\r\n\r\n<script src=\"".toCharArray();
    _jsp_string31 = "/resources/bdp/bootstrap/export/bootstrap-table-export.js\"></script> \r\n<script src=\"".toCharArray();
    _jsp_string8 = "/resources/bdp/bootstrap/css/bootstrap-3.0.3.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n<!--  \u5728\u7ebf\u7f16\u8f91\u5668-->\r\n<link href=\"".toCharArray();
  }
}
